---
swagger: "2.0"
info:
  title: gosea
  version: 1.0.0
  description: gosea - SEA Go Sample Application
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /posts:
    get:
      responses:
        "200":
          description: lists posts
          schema:
            type: array
            items:
              $ref: '#/definitions/post'
  /users:
    get:
      parameters:
      - name: id
        description: UserID
        in: query
        required: false
        type: integer
      responses:
        "200":
          description: Lists users
          schema:
            type: array
            items:
              $ref: '#/definitions/user'
          examples:
            application/json:
            - id: 1
              name: Leanne Graham
              username: Bret
              email: Sincere@april.biz
              address:
                street: Kulas Light
                suite: Apt. 556
                city: Gwenborough
                zipcode: 92998-3874
                geo:
                  lat: -37.3159
                  lng: "81.1496"
              phone: 1-770-736-8031 x56442
              website: hildegard.org
              company:
                name: Romaguera-Crona
                catchPhrase: Multi-layered client-server neural-net
                bs: harness real-time e-markets
      summary: Get Users
      description: Lists Users
definitions:
  post:
    type: object
    properties:
      userId:
        type: object
      id:
        type: object
      title:
        type: string
      body:
        type: string
  user:
    title: Root Type for user
    description: User definition
    type: object
    properties:
      id:
        type: object
      name:
        type: string
      username:
        type: string
      email:
        type: string
      address:
        $ref: '#/definitions/address'
        properties:
          street:
            type: string
          suite:
            type: string
          city:
            type: string
          zipcode:
            type: string
          geo:
            type: object
            properties:
              lat:
                type: string
              lng:
                type: string
      phone:
        type: string
      website:
        type: string
      company:
        $ref: '#/definitions/company'
        properties:
          name:
            type: string
          catchPhrase:
            type: string
          bs:
            type: string
    example:
      id: 1
      name: Leanne Graham
      username: Bret
      email: Sincere@april.biz
      address:
        street: Kulas Light
        suite: Apt. 556
        city: Gwenborough
        zipcode: 92998-3874
        geo:
          lat: -37.3159
          lng: "81.1496"
      phone: 1-770-736-8031 x56442
      website: hildegard.org
      company:
        name: Romaguera-Crona
        catchPhrase: Multi-layered client-server neural-net
        bs: harness real-time e-markets
  address:
    title: Root Type for address
    description: User Adress
    type: object
    properties:
      street:
        type: string
      suite:
        type: string
      city:
        type: string
      zipcode:
        type: string
      geo:
        $ref: '#/definitions/geo'
        properties:
          lat:
            type: string
          lng:
            type: string
    example:
      street: Kulas Light
      suite: Apt. 556
      city: Gwenborough
      zipcode: 92998-3874
      geo:
        lat: -37.3159
        lng: "81.1496"
  company:
    title: Root Type for company
    description: User Company
    type: object
    properties:
      name:
        type: string
      catchPhrase:
        type: string
      bs:
        type: string
    example:
      name: Romaguera-Crona
      catchPhrase: Multi-layered client-server neural-net
      bs: harness real-time e-markets
  geo:
    title: Root Type for geo
    description: Geodata
    type: object
    properties:
      lat:
        type: string
      lng:
        type: string
    example:
      lat: -37.3159
      lng: "81.1496"
